#!/usr/bin/env python

import argparse
import logging
import os
from subprocess import check_call, call

if __name__ == '__main__':
    p = argparse.ArgumentParser(description='Test help script')
    p.add_argument('name', metavar='NAME', type=str, help='name of container')
    p.add_argument('--test', type=str, default='./test.sh', help='test script name')
    args = p.parse_args()

    name = args.name
    test = args.test
    host_cwd = os.getcwd()

    work_dir = '/work'
    data_dir = '/data'

    # Make an image
    res = call(['docker', 'build', '-t', name, '.'])
    if res != 0:
        logging.error('Failed to create an image')
        logging.error('Exit code: %d' % res)
        exit(res)

    failed = False
    # Run test
    res = call(['docker', 'run',
                '--rm',
                '-v', '%s:%s' % (host_cwd, work_dir),
                '-v', '%s:%s:ro' % (data_dir, data_dir),
                '-w', work_dir,
                name,
                test])
    if res != 0:
        logging.error('Failed to run test')
        logging.error('Exit code: %d' % res)
        failed = True

    # chown for clean up
    res = call(['docker', 'run',
                '--rm',
                '-v', '%s:%s' % (host_cwd, work_dir),
                '-w', work_dir,
                name,
                '/bin/bash', '-c',
                'chown `stat -c %u .`:`stat -c %g .` -R .'])
    if res != 0:
        logging.error('Failed to chown')
        logging.error('Exit code: %d' % res)
        failed = True

    if failed:
        exit(1)
